Adding Uruguay's digital political party
github/government.github.com pull request #540
Opened 2017-02-01 03:00 UTC by leog

Partido Digital is the first Uruguayan Open Source digital-based political party where transparency and participation are crucial.

2017-02-01 03:22 UTC, nschonni commented
Think this would probably be more civic tech since it appears to be a political rather than a government (public service) organization.

2017-02-01 03:27 UTC, leog commented
Wow, missed that option. Going for the Civic Hackers then, good catch @nschonni 👍

2017-02-01 03:36 UTC, leog commented
There you go @nschonni!

2017-02-01 03:52 UTC, nschonni requested changes
LGTM, just take a look at the ordering in the file

2017-02-01 03:52 UTC, nschonni commented on _data/civic_hackers.yml
> +  - PartidoDigital
Nit: These files are alphabetical, so it's better to add it above

2017-02-01 04:47 UTC, leog commented
Done @nschonni 🙂

2017-02-02 03:55 UTC, leog commented
Squished commits to have a clear history @nschonni.

2017-02-02 05:20 UTC, nschonni commented
@jbjonesjr LGTM

2017-02-03 23:33 UTC, merged

2017-02-03 23:35 UTC, jbjonesjr commented
:ship: Thanks @leog. Very cool by the way. :heart: that transparency