Some new organisations mainly for France and Sweden
github/government.github.com pull request #674
Opened 2018-03-28 15:16 UTC by PierreMesure

Thanks for the contribution! **Below** is a template that can make it easier when submitting your Organization:

**Your Organization**: I'm a citizen 
**GitHub Organization url**: N/A
**Country/Locality**: N/A

Inclusion requirements:
- [ X ] Referenced account is an [Organization](https://github.com/github/government.github.com#add-organization) not a User^
- [ X ] If this is a government project, your Organization's description should include a reference to your country/agency.
- [ X ] Make sure your Organization includes at least one public repository
- [ X ] Please also include a URL for your organization that links back to your organization or agency homepage.
 
^ If you want to convert your account to an org, details can be found here: https://help.github.com/articles/converting-a-user-into-an-organization/
  
 :heart: GitHub Government Contributors

2018-03-29 08:07 UTC, nschonni requested changes
Awesome, but it looks like three of these are still user accounts, that is why the build is failing

2018-03-29 08:07 UTC, nschonni commented on _data/governments.yml
> +  - GouvernementFR
This is a User rather than an Org

2018-03-29 08:07 UTC, nschonni commented on _data/governments.yml
> +  - SIG-Region-Hauts-de-France
This is a User rather than an Org

2018-03-29 08:07 UTC, nschonni commented on _data/governments.yml
> +  - GoteborgsStad
This is a User rather than an Org

2018-03-29 08:58 UTC, PierreMesure commented
You're right, I missed them! I removed them and will contact the one I know to see if they can change that.

2018-04-03 23:47 UTC, jbjonesjr commented
@PierreMesure @SIG-Region-Hauts-de-France is still listed as a user, not an org.

2018-04-05 16:11 UTC, PierreMesure commented
Done, sorry. I hope it's good now.

2018-04-05 16:39 UTC, nschonni commented
Build failure is unrelated. I've submitted #681 to fix that

2018-04-05 16:41 UTC, nschonni approved these changes

2018-04-05 16:41 UTC, nschonni commented on _data/governments.yml
> -  - sgmap
This one looks like it's moved somewhere else, but the org is still there

2018-04-24 12:38 UTC, PierreMesure commented
Hey, shall we merge this branch?

2018-05-15 13:54 UTC, PierreMesure commented
@jbjonesjr @nschonni Is there anything more to fix to merge that branch?

2018-05-15 15:29 UTC, merged

2018-05-15 15:30 UTC, jbjonesjr commented
all good.